exports.codeBlock = /^\s{4}/
exports.comment = /^\s*\/\/(?!\/) ?(.*)$/
exports.dotLine = /^\s*\.\.\.?(.*)$/
exports.empty = /^\s*$/
exports.excludedComment = /^\s*\/\/\/+/
exports.indentation = /^([\s-]*)(.*)$/
exports.lineEnd = /\r?\n/
// exports.exportsAlias = /^exports\.(\w+) = exports\.(\w+)$/
// exports.exportsConstant = /^exports\.(\w+) = ((?!require).*)$/
// exports.exportsRequire = /^exports\.(\w+) = require\(["'](\.[\w/.]*)["']\)$/
exports.function = /^module\.exports = (?:function )?(\([\w, ]*\))(?: =>)? {$/
exports.genversion = /generated by genversion/i
exports.import = /^import ["'](\.[\w/.]*)["']/
exports.importFrom = /^import .* from ["'](\.[\w/.]*)["']/
// exports.moduleRequire = /^module.exports = require\(["'](\.[\w/.]*)["']\)$/
exports.parameterName = /^(\s+)(\w*)$/
exports.parameterDesc = /^(\s+)(.*)$/
exports.requireModule = /[\s=]require\(["'](\.[\w/.]*)["']\)/
exports.returnValue = /^(\s+)(.*)$/
exports.exampleCode = /^(\s+)(.*)$/
exports.arrayLiteral = /\[([\w,: ]*)\]($|[^(]+)/
exports.objectLiteral = /{([\w,: ]*)}/

exports.nameInSignature = /^([\w .:#/]+)/
exports.nameDepthSeparator = /[- .:#/]/

exports.callSignature = (name) => {
  // Create an expression for name-based signature that
  // begins a valid comment block.
  //
  // Captures the call signature of a function or variable or constant
  // from the comment block. May include parenthesis, for example
  // 'mylib.myfunction(some, params...)' is a valid call signature.
  // Or 'mylib-myfunction[some params ...]' or 'mylib:myfunction',
  // or like, any string after the '// ' syntax.
  //
  // Parameters:
  //   name
  //     a string
  //     OR an array of strings, a list of allowed names.
  //     OR an object of strings, a map from allowed names to their full names.
  //
  // Return
  //   a RegExp
  //

  if (!Array.isArray(name)) {
    // Not an array. Single string or a map.
    if (typeof name === 'object') {
      // Keys contain allowed names.
      name = Object.keys(name)
    } else {
      name = [name]
    }
  }

  // Escape literal dots in names
  const escName = name.map(nam => nam.replace('.', '\\.'))
  // Combine with OR
  const namesPattern = '(' + escName.join('|') + ')'
  // Note JS escapes \\ -> \ and \/ -> /
  const signaturePattern = '^\\s*// #*\\s*(' + namesPattern + '.*)'

  return new RegExp(signaturePattern)
}
