exports.codeBlock = /^\s{4}/
exports.comment = /^\s*\/\/(?!\/) ?(.*)$/
exports.dotLine = /^\s*\.\.\.?(.*)$/
exports.empty = /^\s*$/
exports.indentation = /^(\s*)(.*)$/
exports.lineEnd = /\r?\n/
exports.exportsAlias = /^exports\.(\w+) = exports\.(\w+)$/
exports.exportsConstant = /^exports\.(\w+) = ((?!require).*)$/
exports.exportsRequire = /^exports\.(\w+) = require\('([\w\/\.]+)'\)$/
exports.function = /^module\.exports = (?:function )?(\([\w, ]*\))(?: =>)? {$/
exports.genversion = /generated by genversion/i
exports.hashPath = /\W/g
exports.moduleRequire = /^module.exports = require\('([\w\/\.]+)'\)$/
exports.paramsTitle = /^param(?:eter)?s?:?$/i
exports.returnTitle = /^returns?:?$/i
exports.exampleTitle = /^examples?:?$/i
exports.parameterName = /^(\s+)(\w*)$/
exports.parameterDesc = /^(\s+)(.*)$/
exports.returnValue = /^(\s+)(.*)$/
exports.exampleCode = /^(\s+)(.*)$/
exports.arrayLiteral = /\[([\w,: ]*)\]($|[^(]+)/
exports.objectLiteral = /{([\w,: ]*)}/

exports.callSignature = (name) => {
  // Escape literal dots in names
  const escName = name.replace('.', '\\.')
  // Note JS escapes \\ -> \ and \/ -> /
  const signaturePattern = '^\\s*\/\/ (' + name + '.*)'
  return new RegExp(signaturePattern)
}
